### ISSUE TITLE
xliff-simple-merge fails on unix host

### ISSUE THREAD

**Issue by mpumford** [daniel-sc/xliff-simple-merge#12]
How to reproduce:
$ yarn add -D xliff-simple-merge
$yarn run xliff-simple-merge --help

Result:
yarn run v1.22.19
$ /home/datav/dv-connect/itron/itron-common/node_modules/.bin/xliff-simple-merge --help
/usr/bin/env: ‘node\r’: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

This is caused by the bin file having DOS/Windows line endings.

**Comment by daniel-sc** [comment]
Hi @mpumford thanks for reporting this - would you like to provide a PR for this?

**Comment by mpumford** [comment]
Happy to do so. I've already got a branch with the change on. I just want to make sure it doesn't cause any problems for those using windows.
