### ISSUE TITLE
No way to prevent newlines being added to the merged output

### ISSUE THREAD

**Issue by michaelkrog** [daniel-sc/xliff-simple-merge#19]
I have issues with unwanted newlines in the translated files.

Fx. an extracted messages.xlf may have a unit that looks like this:
```
      <trans-unit id="AccountingView.Connected" datatype="html">
        <source>Connected to <x id="INTERPOLATION" equiv-text="{{system}}"/></source>
        <context-group purpose="location">
          <context context-type="sourcefile">../../accounting/src/lib/settings/settings.component.html</context>
          <context context-type="linenumber">25</context>
        </context-group>
      </trans-unit>
```

When merging that into an existing translated file, using xliff-simpl-merge, I get something like this (newlines added by xliff-simple-merge):
```
      <trans-unit id="AccountingView.Connected" datatype="html">
        <source>
          Connected to 
          <x id="INTERPOLATION" equiv-text="{{system}}"/>
        </source>
        <target state="new">
           Connected to 
          <x id="INTERPOLATION" equiv-text="{{system}}"/>
        </target>
        <context-group purpose="location">
          <context context-type="sourcefile">../../accounting/src/lib/settings/settings.component.html</context>
          <context context-type="linenumber">25</context>
        </context-group>
      </trans-unit>
```

In the end that comes out as new lines in my Angular app as well.

**Comment by michaelkrog** [comment]
PR add here: https://github.com/daniel-sc/xliff-simple-merge/pull/17

**Comment by daniel-sc** [comment]
@michaelkrog thanks for your contribution! You mentioned that you use this lib for Angular - I'd recommend switching to https://github.com/daniel-sc/ng-extract-i18n-merge ;)

**Comment by michaelkrog** [comment]
@daniel-sc Thanks for the heads up.

I have a rather sophisticated setup with several app depending on library A which in turn depends on library B - and both A and B contains translated strings in their build. In the apps I merge it all together.

I had issues getting it all to work with [ng-extract-i18n-merge](https://github.com/daniel-sc/ng-extract-i18n-merge), a few years back, but maybe I should give it a go again.

**Comment by michaelkrog** [comment]
@daniel-sc By the way.

Would it be possible to you to create a new release including the changes for this issue?
