### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'attr')

### ISSUE THREAD

**Issue by atix9000** [daniel-sc/xliff-simple-merge#5]
xliff-simple-merge --input-file messages.xlf --destination-file messages.de.xlf -output-file output.xlf
...npm\node_modules\xliff-simple-merge\dist\src\merge.js:54
            destUnit.childNamed('target').attr.state = 'new';
                                         ^

TypeError: Cannot read properties of undefined (reading 'attr')

**Comment by daniel-sc** [comment]
Hi @atix9000 
Would it be possible to share input and target files? (At least anonymized)

**Comment by atix9000** [comment]
@daniel-sc in destination-file there was no <target> tag, so i added empty <target> tag and it is working. It would be good to add auto create <target> tag option.

Thanks for the library helped me a lot :)

**Comment by filol** [comment]
Hello @daniel-sc i got the same bug on my side :)
