### ISSUE TITLE
Merge changes to notes

### ISSUE THREAD

**Issue by demilsson** [daniel-sc/xliff-simple-merge#6]
It seems like no changes to `<note>` items are carried over from the source file to the destination file. 

For example, if a `trans-unit` already exists in the target file and the `<note from="description">` for the unit has been updated in the source file, the updated description will not carry over into the destination file.

It feels like the expected behaviour would be that everything in the `<trans-unit>` should be updated, except for the `<target>`.

**Comment by daniel-sc** [comment]
@demilsson Thanks for reporting this. Your expectation sounds reasonable. 

Would you like to contribute a PR, as I'm not sure I find time for this in the next weeks..?

**Comment by ablomq** [comment]
Yes I noted that too. When I update or add new meaning / descriptions they are not carried over to the destination file. When can we expect this issue to be resolved?

**Comment by daniel-sc** [comment]
I'll probably fix this in the next days..
